#!/usr/bin/env python3
"""Validate canonical JSON schemas and refresh checked-in contract metadata."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_ROOT = ROOT / "schemas"


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def validate_schema(path: Path, value: dict) -> None:
    required = {"$schema", "$id", "title", "type", "properties"}
    missing = required - value.keys()
    if missing:
        raise SystemExit(f"{path}: missing schema keys: {sorted(missing)}")
    if value["type"] != "object":
        raise SystemExit(f"{path}: top-level schema must be an object")
    if not value["$id"].startswith("https://github.com/caniko/topomind/"):
        raise SystemExit(f"{path}: schema id must be owned by caniko/topomind")
    if not isinstance(value.get("properties"), dict):
        raise SystemExit(f"{path}: properties must be an object")
    for key in value.get("required", []):
        if key not in value["properties"]:
            raise SystemExit(f"{path}: required field {key!r} is not declared")


def main() -> None:
    entries = []
    for path in sorted(SCHEMA_ROOT.rglob("*.json")):
        if "generated" in path.parts:
            continue
        value = json.loads(path.read_text(encoding="utf-8"))
        validate_schema(path, value)
        relative = path.relative_to(ROOT).as_posix()
        entries.append({"path": relative, "id": value["$id"], "title": value["title"], "sha256": hashlib.sha256(canonical(value)).hexdigest()})
    manifest = {"schema_version": "manifest/1.0", "schemas": entries}
    generated = SCHEMA_ROOT / "generated"
    generated.mkdir(exist_ok=True)
    (generated / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    python = "# Generated by scripts/validate_schemas.py.\nSCHEMAS = " + repr({entry["path"]: entry for entry in entries}) + "\n"
    addon_manifest = ROOT / "freecad-addon/SemanticMCP/schema_manifest.py"
    addon_manifest.write_text(python, encoding="utf-8")
    print(f"validated {len(entries)} schemas")


if __name__ == "__main__":
    main()
